services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: SimpleInterest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
        
  flyway:
    image: flyway/flyway
    volumes:
      - ./db/sql:/flyway/sql
      - ./db:/flyway/conf
    environment:
      - FLYWAY_URL=jdbc:mariadb://173.249.33.42:3306/SimpleInterest
      - FLYWAY_USER=user
      - FLYWAY_PASSWORD=password
    depends_on:
      - db
  
  
  api:
    image: julianhesberg/simpleinterestcalculator-api:staging
    depends_on:
      - db
    ports:
      - 5001:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: julianhesberg/simpleinterestcalculator-frontend:staging
    depends_on:
      - api
    ports:
      - 5002:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8081:8080
