services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: SimpleInterest
    ports:
      - 5432:5432
        
  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    depends_on:
      - db
  
  api:
    image: julianhesberg/simpleinterestcalculator-api:staging
    depends_on:
      - db
    ports:
      - 173.249.33.42:5001:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: julianhesberg/simpleinterestcalculator-frontend:staging
    depends_on:
      - api
    ports:
      - 173.249.33.42:5002:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8081:8080
